version: '3.7'

services:
  backend:
    image: tronglu.auth-service:${VERSION}
    env_file:
      - .env
      - .env.production
    build: .
    environment:
      NODE_ENV: production
    ports:
      - ${PORT}:${PORT}
