version: '3.7'

services:
  backend:
    image: lvhtrong.auth-service
    env_file:
      - .env
      - .env.local
      - .env.production
      - .env.production.local
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
