version: '3.7'

services:
  backend:
    image: tronglu.auth-service:${VERSION}
    env_file:
      - .env
      - .env.production
    build: .
    environment:
      NODE_ENV: production
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    network_mode: host
  database:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - data-volume:/var/tronglu.auth-service/db

volumes:
  data-volume:
