version: '3.7'

services:
  backend:
    image: tronglu.auth-service
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - data-volume:/var/tronglu.auth-service/db

volumes:
  data-volume:
